#!/bin/bash
#!/bin/bash

#PBS -l select=1:ncpus=16:ngpus=2:mem=92gb
#PBS -l walltime=02:00:00
#PBS -M renee.lu@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5160268/Output117_wav2vec_Report

# Go into thesis folder
cd /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis

# Activate virtual environment
source thesis_env/bin/activate

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/wav2vec_projects/output/output150.txt

cd /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/wav2vec_projects/

# Run pretrain script
fairseq-hydra-train \
    task.data=/srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/myST-OGI-TLT-CU_local/THESIS_C/manifest \
    --config-dir /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/myST-OGI-TLT-CU_local/THESIS_C \
    --config-name wav2vec2_base_kids_draft 2>&1 | tee output/output150.txt
