#!/bin/bash
#!/bin/bash

#PBS -l select=1:ncpus=32:ngpus=4:mem=184gb
#PBS -l walltime=70:00:00
#PBS -M renee.lu@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5160268/Output117_wav2vec_Report

# Go into thesis folder
cd /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis

# Activate virtual environment
source thesis_env/bin/activate

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/wav2vec_projects/output/output194.txt

cd /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/wav2vec_projects/

python THESIS_C/run_finetune_kids_myST-OGI-TLT-halved.py 2>&1 | tee -a /srv/scratch/z5160268/2020_TasteofResearch/kaldi/egs/renee_thesis/s5/wav2vec_projects/output/output194.txt

